config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    namespace :blog do
      resources :posts
    end
  end

  get 'blog/:year/:month/:day/:id', to: 'blog/posts#show',
    constraints: { year: /\d{4}/, month: /\d{1,2}/, day: /\d{2}/ },
    as: :blog_post

  root to: 'admin/blog/posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
module Blog
  def self.table_name_prefix
    'blog_'
  end
end

app/models/blog/post.rb
class Blog::Post < ApplicationRecord
end

app/controllers/admin/blog/posts_controller.rb
class Admin::Blog::PostsController < ApplicationController

  def index
    @posts = ::Blog::Post.all
  end

  def new
    @post = ::Blog::Post.new
  end

  def create
    @post = ::Blog::Post.new post_params

    if @post.save
      redirect_to admin_blog_posts_path, notice: t('.created')
    else
      render :new
    end
  end

  def edit
    @post = ::Blog::Post.find params[:id]
  end

  def update
    @post = ::Blog::Post.find params[:id]

    if @post.update_attributes post_params
      redirect_to admin_blog_posts_path, notice: t('.updated')
    else
      render :edit
    end
  end

  def destroy
    @post = ::Blog::Post.find params[:id]

    if @post.destroy
      redirect_to admin_blog_posts_path, notice: t('.destroyed')
    else
      redirect_to admin_blog_posts_path, errors: t('.not_destroyed')
    end
  end

  private

  def post_params
    params.require(:blog_post).permit(:title, :post, :subtitle, :description,
      :author)
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def button_link_to(*args, &block)
    link_to *args, class: 'button', &block
  end
end

app/helpers/blog/posts_helper.rb
module Blog
  module PostsHelper
    def link_to_post(label, post, options, &block)
      if block_given?
        link_to blog_post_path(post.created_at.year, post.created_at.month, post.created_at.day, post.id), options, &block
      else
        link_to label, blog_post_path(post.created_at.year, post.created_at.month, post.created_at.day, post.id), options
      end
    end
  end
end

app/views/admin/blog/posts/_form.html.haml
.content
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :post
    = f.text_area :post, rows: 35, class: 'tinymce'

%aside
  .field
    = f.label :subtitle
    = f.text_field :subtitle

  .field-group
    .header
      %h2 Meta Data
    .fields
      .field
        = f.label :description
        = f.text_area :description
      .field
        = f.label :author
        = f.text_field :author
  .field
    = f.submit

app/views/admin/blog/posts/_post.html.haml
%tr{id: dom_id(post), class: dom_class(post) }
  %td= check_box_tag 'post_ids[]', post.id, false, id: "post_id_#{post.id}"
  %td
    %strong= link_to post.title, edit_admin_blog_post_path(post)
    .row-actions
      %span.edit= link_to 'Edit', edit_admin_blog_post_path(post)
      %span.delete= link_to 'Delete', admin_blog_post_path(post), method: :delete, data: { confirm: 'Are you sure?' }
      %span.view
        = link_to blog_post_path(post.created_at.year, post.created_at.month, post.created_at.day, post.id), 'View', target: '_blank'
  %td= post.author
  %td
  %td -
  %td
    Published
    %br
    = post.created_at.to_formatted_s(:dmy)

app/views/admin/blog/posts/edit.html.haml
%h1 Edit Blog Post

= form_for @post, url: admin_blog_post_path(@post) do |f|
  = render 'form', f: f

app/views/admin/blog/posts/index.html.haml
.actions
  = button_link_to 'New Blog Post', new_admin_blog_post_path

%h1 Posts

%table#blog_posts.listing
  %thead
    %tr
      %th.select= check_box_tag :all
      %th.title Title
      %th.author Author
      %th.categories Categories
      %th.comments Comments
      %th.date Date
  %tbody
    = render partial: 'admin/blog/posts/post', collection: @posts

app/views/admin/blog/posts/new.html.haml
%h1 New Post

= form_for @post, url: admin_blog_posts_path do |f|
  = render 'form', f: f

app/views/layouts/application.html.haml
!!! 5
%html{lang: I18n.locale}
  %head
    %title Broken App
    %meta{charset: 'utf-8'}
    %meta{content: 'IE=edge', 'http-equiv': 'X-UA-Compatible'}
    %meta{name: 'viewport', content: 'initial-scale=1, maximum-scale=1'}
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    %main
      .content-container
        = yield